### PR TITLE
green color and added aesthetics. HabibiDevs edit, finishing touches.

### PR DESCRIPTION
**Pull request by BujiRensO**
Screenshot (493)

### CODE REVIEW

**Comment by BujiRensO** [comment]
Screenshot (494)

**Comment by BujiRensO** [comment]
Box Shadow
Screenshot (495)

**Comment by SiLawrinz** [comment]
wow, that is amazing!

**Comment by irvento** [comment]
woah ser, u got a big weapon

**Comment by BujiRensO** [comment]
> wow, that is amazing!

Thank you sir! Appreciate it

**Comment by SiLawrinz** [comment]
yo ang font sa view team website ba, e lahi kahag shade nga green or e change nalang mismo ang font style.

**Comment by SiLawrinz** [comment]
> yo ang font sa view team website ba, e lahi kahag shade nga green or e change nalang mismo ang font style.

labun wapa na merge

**Comment by BujiRensO** [comment]
> > yo ang font sa view team website ba, e lahi kahag shade nga green or e change nalang mismo ang font style.
> 
> labun wapa na merge
> 

Okay sir! 🫡

**Comment by BujiRensO** [comment]
> > > yo ang font sa view team website ba, e lahi kahag shade nga green or e change nalang mismo ang font style.
> > 
> > 
> > labun wapa na merge
> 
> Okay sir! 🫡

How about that, I've changed the font. also made changes at the header and box shadow.

**Comment by SiLawrinz** [comment]
> > > > yo ang font sa view team website ba, e lahi kahag shade nga green or e change nalang mismo ang font style.
> > > 
> > > 
> > > labun wapa na merge
> > 
> > 
> > Okay sir! 🫡
> 
> How about that, I've changed the font. also made changes also at the header and box shadow.

Wow, That is awesome, great job! :)

**Comment by cliffamadeus** [comment]
LGTM

**Comment by BujiRensO** [comment]
> LGTM

Thank you sir!

**Comment by JoeannCarlos88** [comment]
< img > srcl" your Joeann Carlos , image . jpg" 
Class= " left e3- circle
w3- . mpargin - right " alt" Your Joeann 
 carlos">

**Pull request merged**
