### PR TITLE
Removed Excess hamood.html gi sugo ni junard oblak

### PR DESCRIPTION
**Pull request by SiLawrinz**
Amoang gi delete kay dugangdugang sa file

### CODE REVIEW

**Comment by SendHelp001** [comment]
kinsa si junard

**Comment by SiLawrinz** [comment]
**[Akong love of my life]**

**Comment by BujiRensO** [comment]
Nara si Jonard oh

https://youtu.be/FQEzsScwWCA?si=tH5wUIzH-qfSLgHN

**Comment by Dsovichy** [comment]
https://www.youtube.com/watch?v=Mu_pHPGSKkM&t=68s

**Comment by Dsovichy** [comment]
> https://www.youtube.com/watch?v=Mu_pHPGSKkM&t=68s

https://www.facebook.com/PhilstikTrends/videos/7846598842017203/?mibextid=zDhOQc

**Comment by irvento** [comment]
https://rb.gy/ci7xsw

**Comment by hexedhorizon** [comment]
Naa ra murags Jonard https://www.facebook.com/reel/344957324661888

**Pull request merged**
